version: '3.6'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:javhar12@db/test
    networks:
      - app
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: javhar12
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - app
    ports:
      - 5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  app:
    driver: bridge